name = input("What is your name? ")
age = input("What is your age? ")
location = input("What is your location? ")
print ("Hello " + name + ", you are " + age + " years old and live in " + location + ".")
print("End of the program")
print("Thank you for using the program")